### ISSUE TITLE
Client-side encryption

### ISSUE THREAD

**Issue by JordanCola** [SD-Paranoia/Paranoia#2]
Get message encryption up and running on the client application.

**Comment by JordanCola** [comment]
I have created some code to generate a new symmetric key and store it on the device, as well as encrypt and decrypt using that key. This code can be found in the [encryption-implementation](https://github.com/SD-Paranoia/Paranoia/tree/encryption-implementation) branch. 
I need to work on storing multiple keys and we'll need to figure out transmission of IV for proper decryption on the recipient device. Code will need to be cleaned up as well.

**Comment by TheToddLuci0** [comment]
Implemented, closing.
